name: Bump Action version

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 0

      - name: Update dirty-waters-action version
        run: |
          COMMIT_SHA=$(git rev-parse HEAD)

          # Use sed to update occurrences of the version in the workflow file
          sed -i "s/chains-project\/dirty-waters-action@v[0-9.]\+/chains-project\/dirty-waters-action@${COMMIT_SHA}/g" ./example_workflow.yml

          echo "commit_sha=$COMMIT_SHA" >> $GITHUB_ENV

      - name: Update dirty_waters_version in the example workflow to the repo's latest tag
        run: |
          LATEST_TAG=$(git ls-remote --tags https://github.com/chains-project/dirty-waters.git | awk -F/ '{print $3}' | sort -V | tail -n1)
          sed -i "s/dirty_waters_version: v[0-9.]\+/dirty_waters_version: ${LATEST_TAG}/g" ./example_workflow.yml

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5.1.0
        with:
          commit_message: "Bump dirty-waters-action version to ${{ env.commit_sha }}"
          branch: ${{ github.head_ref }}
