name: Bump Action version

on:
  workflow_run:
    workflows: ["Publish Release Tag"]
    types:
      - completed
    branches:
      - main
  workflow_dispatch:

jobs:
  update-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 0

      - name: Get latest tag from this repository
        id: get-latest-tag
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0)
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

      - name: Update dirty-waters-action version to latest tag
        run: |
          # Use sed to update occurrences of the version in the workflow file with latest tag
          sed -i 's/chains-project\/dirty-waters-action@v[0-9.]\+/chains-project\/dirty-waters-action@'"$LATEST_TAG"'/g' ./example_workflow.yml

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v6.0.1
        with:
          commit_message: "Bump dirty-waters-action version to ${{ env.LATEST_TAG }}"
          branch: ${{ github.head_ref }}
