name: Dirty Waters Analysis

on:
  pull_request:
    paths:
      - "**/package.json"
      - "**/package-lock.json"
      - "**/yarn.lock"
      - "**/pnpm-lock.yaml"
      - "**/pom.xml"
  push:
    branches:
      - main
      - master
    paths:
      - "**/package.json"
      - "**/package-lock.json"
      - "**/yarn.lock"
      - "**/pnpm-lock.yaml"
      - "**/pom.xml"
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if first dirty-waters run
        id: check-first-run
        run: |
          WORKFLOW_FILE=$(gh api repos/${{ github.repository }}/actions/workflows --jq '.workflows[] | select(.name == "${{ github.workflow }}") | .path' | xargs basename)
          RUNS=$(gh api repos/${{ github.repository }}/actions/workflows/$WORKFLOW_FILE/runs --jq '[.workflow_runs[] | select(.conclusion=="success")] | length')
          echo "is_first_run=$([[ $RUNS -le 1 ]] && echo 'true' || echo 'false')" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Static Dirty Waters analysis
        id: static-analysis
        if: steps.check-first-run.outputs.is_first_run == 'true'
        uses: chains-project/dirty-waters-action@v1.5
        with:
          # example args, change as needed
          github_token: ${{ secrets.GITHUB_TOKEN }}
          project_repo: ${{ github.repository }}
          package_manager: npm # Change this according to your project
          allow_pr_comment: true # Optional: comments on PRs if high severity issues are found
          comment_on_commit: true # Optional: comments on commits (if not PR/if above is false) if high severity issues are found
          latest_commit_sha: ${{ github.sha }}
          github_event_before: ${{ github.event.before }}

      - name: Run Differential Dirty Waters Analysis
        id: differential-analysis
        if: steps.check-first-run.outputs.is_first_run != 'true'
        uses: chains-project/dirty-waters-action@v1.5
        with:
          # example args, change as needed
          github_token: ${{ secrets.GITHUB_TOKEN }}
          project_repo: ${{ github.repository }}
          differential_analysis: true
          package_manager: npm # Change this according to your project
          allow_pr_comment: true # Optional: comments on PRs if high severity issues are found
          comment_on_commit: true # Optional: comments on commits (if not PR/if above is false) if high severity issues are found
          latest_commit_sha: ${{ github.sha }}
          github_event_before: ${{ github.event.before }}
