name: Handle Issue Checkbox Updates

on:
  issues:
    types: [edited]

jobs:
  process-checkboxes:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Set up Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: "3.13.6"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub==2.6.1

      - name: Process checked items
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_TITLE: "Check Dirty-Waters Updates"
        run: |
          python .github/scripts/process_checkboxes.py
