name: Test Action
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test Action
        uses: ./
        with:
          project_repo: ${{ github.repository }}
          version_old: ${{ github.ref_name }}
          package_manager: npm
          fail_on_high_severity: true
          comment_on_pr: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
